export enum ModuleName {
  AUTH = "auth",
  HOME = "home",
  COURSE = "course",
  GROWCAP = "growCap",
  LEARNCAP = "learnCap",
  LIFECAP = "lifeCap",
  CHALLENGECAP = "challengeCap",
  AI = "ai",
  SUCCESSIONPLAN = "succession-plan",
  EXPERIENCEINITIATIVE = "experience-initiative",
  EXPREANDSUCCE = "expre-and-succe",
  PLANRESULT = "plan-result",
  INITIATIVERESULT = "initiative-result",
  BUILD_LESSON = "build-lesson",
  LESSON_FORM = "lesson-form",
  LESSON_RESULT = "lesson-result",
  PROMPT_LESSON = "prompt-lesson",
  STEM_LESSON = "stem-lesson",
  ASSISTANTAI = "assistant-ai",
  BUILD_TOPIC = "build-topic", 
  PERSONAL_PLAN = "personal-plan",
  TEACHER_ASSISTANT = "teacher-assistant",
  BUILD_STRUCTURE = "build-structure",
  EXAM_PREVIEW = "exam-preview"
}

export enum PageName {
  LOGIN = "login",
  REGISTER = "register",
  HOME = "home",
  COURSE_DETAIL = "CourseDetail",
  CATEGORY_COURSES = "CategoryCourses",
  LESSON_PLAYER = "LessonPlayerPage",
  GROWCAP = "growCap",
  LEARNCAP = "learnCap",
  LIFECAP = "lifeCap",
  CHALLENGECAP = "challengeCap",
  AI = "ai",
  SUCCESSIONPLAN = "succession-plan",
  EXPERIENCEINITIATIVE = "experience-initiative",
  EXPREANDSUCCE = "expre-and-succe",
  PLANRESULT = "plan-result",
  INITIATIVERESULT = "initiative-result",
  LESSON_FORM = "lesson-form",
  LESSON_RESULT = "lesson-result",
  PROMPT_LESSON = "prompt-lesson",
  STEM_LESSON = "stem-lesson",
  ASSISTANTAI = "assistant-ai",
  BUILD_TOPIC = "build-topic",
  BUILD_LESSON = "build-lesson",
  PERSONAL_PLAN = "personal-plan",
  TEACHER_ASSISTANT = "teacher-assistant",
  BUILD_STRUCTURE = "build-structure",
  EXAM_PREVIEW = "exam-preview"
}

export enum PagePath {
  NOT_FOUND = "/not-found",
  LOGIN = "/login",
  REGISTER = "/register",
  HOME = "/",
  GROWCAP = "/grow-cap",
  LEARNCAP = "/learn-cap",
  LIFECAP = "/life-cap",
  CHALLENGECAP = "/challenge-cap",
  AI = "/ai",
  SUCCESSIONPLAN = "/ai/succession-plan",
  EXPERIENCEINITIATIVE = "/ai/experience-initiative",
  EXPREANDSUCCE = "/ai/expre-and-succe",
  PLANRESULT = "/ai/plan-result",
  INITIATIVERESULT = "/ai/initiative-result",
  COURSE_DETAIL = "courses/:id",
  CATEGORY_COURSES = "categories/:categoryId/courses",
  LESSON_DETAIL = "lesson/:id",
  LESSON_FORM = "/ai/lesson-form",
  LESSON_RESULT = "/ai/lesson-result",
  PROMPT_LESSON = "/ai/prompt-lesson",
  STEM_LESSON = "/ai/stem-lesson",
  ASSISTANTAI = "/ai/assistant-ai",

  // Student pages
  STUDENT_EXERCISE = "/ai/student/exercise",
  STUDENT_REVIEW = "/ai/student/review",
  STUDENT_MINDMAP = "/ai/student/mindmap",
  STUDENT_PLAN = "/ai/student/plan",
  BUILD_TOPIC = "/ai/build-topic",
  BUILD_LESSON = "/ai/build-lesson",
  PERSONAL_PLAN = "/ai/personal-plan",
  TEACHER_ASSISTANT = "/ai/teacher-assistant",
  BUILD_STRUCTURE = "/ai/build-structure",
  EXAM_PREVIEW = "/ai/exam-preview"
}