export enum ModuleName {
  AUTH = "auth",
  HOME = "home",
  GROWCAP = "growCap",
  LEARNCAP = "learnCap",
  LIFECAP = "lifeCap",
  CHALLENGECAP = "challengeCap",
  AI = "ai",
  SUCCESSIONPLAN = "succession-plan",
  EXPERIENCEINITIATIVE = "experience-initiative",
  EXPREANDSUCCE = "expre-and-succe",
  PLANRESULT = "plan-result",
  INITIATIVERESULT = "initiative-result",
}

export enum PageName {
  LOGIN = "login",
  REGISTER = "register",
  HOME = "home",
  GROWCAP = "growCap",
  LEARNCAP = "learnCap",
  LIFECAP = "lifeCap",
  CHALLENGECAP = "challengeCap",
  AI = "ai",
  SUCCESSIONPLAN = "succession-plan",
  EXPERIENCEINITIATIVE = "experience-initiative",
  EXPREANDSUCCE = "expre-and-succe",
  PLANRESULT = "plan-result",
  INITIATIVERESULT = "initiative-result",
}

export enum PagePath {
  NOT_FOUND = "/not-found",
  LOGIN = "/login",
  REGISTER = "/register",
  HOME = "/home",
  GROWCAP = "/grow-cap",
  LEARNCAP = "/learn-cap",
  LIFECAP = "/life-cap",
  CHALLENGECAP = "/challenge-cap",
  AI = "/ai",
  SUCCESSIONPLAN = "succession-plan",
  EXPERIENCEINITIATIVE = "experience-initiative",
  EXPREANDSUCCE = "expre-and-succe",
  PLANRESULT = "plan-result",
  INITIATIVERESULT = "initiative-result",
}